#!/usr/bin/expect
set timeout 18000
set source     [lindex $argv 0]
set host [lindex $argv 1]
set pass [lindex $argv 2]
spawn scp -r $source $host
expect {
"(yes/no)?" { send "yes\r" ;exp_continue }
"password:" { send "$pass\r" ;exp_continue }
} 
#expect eof

